# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://lhjnano.github.io
date_format: "ordinal"
title: "HeonJe Lee's Record"
subtitle: "Records of On-premise"
description: ""
keywords: Devops, System, Linux
timezone: Asia/South Korea
encoding: "utf-8"
since: 2024
repository: lhjnano/lhjnano.github.io

cdn:
    jsdelivr:
        enabled: false

components:
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: false
        hide-platforms: weibo,qq,wechat,douban,qzone,facebook,twitter
    # 방문 통계
    busuanzi:
        enabled: true
        start_date: 2024-05-03
    # Github Repositories
    side_bar_repo:
        enabled: true
        limit: 5
    # 단어 수 세기
    word_count:
        enabled: true
    # 화면 오른 쪽 상단 모서리의 QR 코드
    #  assets/images/qrcode.jpg
    qrcode:
        enabled: false
    # wifi 인덱스 페이지 (list/cate)
    wiki:
        view: cate
    # 사진 라이트 박스 효과
    fancybox:
        enabled: false
# 페이지 콘텐츠 압축
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 코드 강조 스타일 지원 theme, Ref: https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: HeonJe Lee
organization: 
organization_url: 
github_username: lhjnano
location: Inchoen, Korea
email: lhjnano@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 시작

  -
    href: /categories/
    label: 카테고리

  -
    href: /wiki/
    label: 위키

  -
    href: /links/
    label: 링크
    mobile-hidden: true

  -
    href: /about/
    label: 소개

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      INDEX       #
# ---------------- #
index:
    banner:
        # 시작 banner 텍스트색
        color: "#fff"
        # 시작 네비게이션 텍스트색
        nav-color: "rgba(255, 255, 255, .5)"
        # 시작 banner 배경색
        background-color: "#4183c4"
        # 시작 banner 배경 이미지
        # background-image: "/assets/images/octicons-bg.png"
        # background-repeat: "no-repeat"
        # background-size: "cover"

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
    fragments:
        output: true
        permalink: /fragment/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk, utterances, beaudar, giscus
comments_provider: utterances
# !!!Important!!! Please modify infos below to yours
# utterances ：https://utteranc.es/
utterances:
    repo: lhjnano/blog-comments


# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 전체 텍스트 검색 지원 여부
    fulltext: false
    # 최대 결과 수
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
#     analytics_id: # G-20FLEG5Q2W
    adsense:
        enabled: true
        footer: true
        sidebar: true
        sidebar-detail: false
        content_header: false
        content_footer: false
