# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://lhjnano.github.io
date_format: "ordinal"
title: "HeonJe Lee's Record"
subtitle: "Records of On-premise"
description: "Share HeonJe Lee's development skills."
keywords: Devops, System, Linux
timezone: Asia/South Korea
encoding: "utf-8"
since: 2024
repository: lhjnano/lhjnano.github.io

cdn:
  jsdelivr:
    enabled: false

components:
  share:
    enabled: false
    hide-platforms: linkedin,facebook,twitter
  busuanzi:
    enabled: true
    start_date: 2024-05-03
  side_bar_repo:
    enabled: true
    limit: 5
  word_count:
    enabled: true
  qrcode:
    enabled: false
  fancybox:
    enabled: false
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: HeonJe Lee
organization:
organization_url:
github_username: lhjnano
location: Incheon, Korea
email: lhjnano@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  - href: /
    label: HOME
  - href: /categories/
    label: CATEGORY
  - href: /fragments/
    label: BOOKS
  - href: /about/
    label: ABOUT ME

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      INDEX       #
# ---------------- #
index:
  banner:
    color: "#fff"
    nav-color: "rgba(255, 255, 255, .5)"
    background-color: "#2c3e50"

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-github-metadata
  - rouge
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-toc
  - jemoji
collections:
  fragments:
    output: true
    permalink: /fragment/:path/

# ---------------- #
#      Comments    #
# ---------------- #
comments_provider: utterances
utterances:
  repo: lhjnano/blog-comments

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
  fulltext: false
  limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
  adsense:
    enabled: true
    sidebar: true
