name: Update Notion Data

on:
  schedule:
    - cron: "0 9 * * *" # 매 시간마다 실행
  workflow_dispatch: # 수동 실행 가능

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    steps:
      # 저장소 클론
      - name: Checkout repository
        uses: actions/checkout@v3

      # Notion 데이터 가져오기
      - name: Fetch Notion Data
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.HABIT_DATABASE_ID }}
        run: |
          curl -X POST "https://api.notion.com/v1/databases/$DATABASE_ID/query" \
            -H "Authorization: Bearer $NOTION_TOKEN" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" > notion_data.json

      # GitHub Pages 브랜치에 반영
      - name: Update GitHub Pages
        run: |
          mkdir -p output
          mv notion_data.json output/
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@github.com"
          git add output/notion_data.json
          git commit -m "Update Notion data"
          git push origin master
